In [36]:
import numpy as np 
from sklearn.base import BaseEstimator
from sklearn.model_selection import train_test_split
import pandas as pd 
from sklearn.preprocessing import LabelEncoder

In [37]:
df = pd.read_csv('../00.data/diabetes.csv')

In [38]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [39]:
df.shape

(768, 9)

In [40]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [41]:
zero_features = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin','BMI']
for feature in zero_features:
    zero_count = df[df[feature] == 0][feature].count()
    print(f'{feature} 0 건수는 {zero_count}, 비율은 {zero_count/768:.4f}')

Glucose 0 건수는 5, 비율은 0.0065
BloodPressure 0 건수는 35, 비율은 0.0456
SkinThickness 0 건수는 227, 비율은 0.2956
Insulin 0 건수는 374, 비율은 0.4870
BMI 0 건수는 11, 비율은 0.0143


In [43]:
X = df.iloc[:,:-1]
y = df.iloc[:, -1]

In [45]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [46]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=2021)

In [47]:
from sklearn.linear_model import LogisticRegression

In [50]:
lr_clf = LogisticRegression()
lr_clf.fit(X_train, y_train)
pred = lr_clf.predict(X_test)

In [51]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[88,  9],
       [24, 33]], dtype=int64)

In [52]:
# 정밀도 (Precision)
from sklearn.metrics import precision_score
precision_score(y_test, pred)

0.7857142857142857

In [53]:
# 재현율 (recall)
from sklearn.metrics import recall_score
recall_score(y_test, pred)

0.5789473684210527

In [54]:
# F1 score
from sklearn.metrics import f1_score
f1_score(y_test, pred)

0.6666666666666667

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.7857142857142857

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [29]:
df['BloodPressure'].value_counts()

70     57
74     52
78     45
68     45
72     44
64     43
80     40
76     39
60     37
0      35
62     34
82     30
66     30
88     25
84     23
90     22
58     21
86     21
50     13
56     12
54     11
52     11
92      8
75      8
65      7
85      6
94      6
48      5
96      4
44      4
110     3
106     3
100     3
98      3
108     2
104     2
46      2
55      2
30      2
95      1
61      1
102     1
38      1
40      1
24      1
114     1
122     1
Name: BloodPressure, dtype: int64

In [27]:
df['Glucose'].value_counts()

99     17
100    17
129    14
125    14
106    14
       ..
169     1
61      1
178     1
177     1
199     1
Name: Glucose, Length: 136, dtype: int64

In [ ]:
df['DiabetesPedigreeFunction'].value_counts()

In [6]:
X = df.drop('Outcome',axis=1).values
y = df['Outcome'].values

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2021)

In [11]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression()
lr_clf.fit(X_train, y_train)
pred = lr_clf.predict(X_test)

C:\Users\yongmimi\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
pred_proba = lr_clf.predict_proba(X_test)
pred_proba[:5]

array([[0.30975396, 0.69024604],
       [0.23655984, 0.76344016],
       [0.97282494, 0.02717506],
       [0.41121719, 0.58878281],
       [0.79489503, 0.20510497]])

In [13]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[87, 10],
       [27, 30]], dtype=int64)

In [14]:
# 정밀도 (Precision)
from sklearn.metrics import precision_score
precision_score(y_test, pred)

0.75

In [15]:
# 재현율 (recall)
from sklearn.metrics import recall_score
recall_score(y_test, pred)

0.5263157894736842

In [16]:
# F1 score
from sklearn.metrics import f1_score
f1_score(y_test, pred)

0.6185567010309279

In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.7597402597402597